### ISSUE TITLE
Readme details

### ISSUE THREAD

**Issue by slrslr** [weakish/0net-snapshot#1]
The readme file does not explain
- why snapshot is useful
- where the snapshot will be saved
- how the snapshot will look like

**Comment by weakish** [comment]
Thanks for feedback.

I clarify the snapshots are based on git repository,
(answering the "will look like" question)
and the root directory of git repository
(answering the "will be saved" question).

> why snapshot is useful

I leave out this,
because I think the reason is obvious.
Backup is important, and history is important.
